services:
  db:
    image: mysql:8.0
    container_name: synk_database
    restart: always

    env_file: .env
    
    command: --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

    ports:
      - "3306:3306"

    volumes:
      - ./mysql_data:/var/lib/mysql

    networks:
      - synk_network

networks:
  synk_network:
    external: true